name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.2"
      
      - name: Install dependencies
        run: go mod download

      - name: Set up sqlc
        uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: "1.29.0"

      - name: Check sqlc diff
        run: sqlc diff

      - name: Build
        run: go build -v ./...

      - name: Build with coverage
        run: go test -coverprofile=coverage.txt ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
